[package]
name    = "lex-code"
version = "0.1.0"
lex     = "0.9.5"

[dependencies]
"lex-llm"    = { path = "../lex-llm" }
"lex-agent"  = { path = "../lex-agent" }
"lex-trail"  = { path = "../lex-trail" }
"lex-spec"   = { path = "../lex-spec" }
"lex-schema" = { path = "../lex-schema" }

[bin]
name = "lex-code"
path = "src/tui/main.lex"
