# find_packages — search existing Lex packages before building your own.
#
# The overlap problem this fixes: an agent with no view of what already
# exists rebuilds it (e.g. reimplementing a crypto library that shipped as
# lex-crypto). This queries the org package catalog — every lex-* package's
# name, description, and exported function signatures — so the model can
# discover and reuse (import a git dep) instead of reinventing.
#
# Backed by the static catalog the hub console serves (generated by scanning
# the org). Read-only, network-only.

import "std.process" as proc

import "std.str" as str

import "std.list" as list

import "lex-llm/tool" as t

import "lex-schema/json_value" as jv

import "lex-schema/error" as e

import "lex-schema/schema" as s

import "./util" as util

fn catalog_url() -> Str {
  "https://console.lexlang.org/catalog.json"
}

fn params() -> s.ModelSchema {
  { title: "FindPackagesArgs", description: "Search existing Lex packages by name, description, or exported function (e.g. \"gcd\", \"jwt\", \"base32\") before writing your own", fields: [s.required_str("query", [])] }
}

fn sfield(j :: jv.Json, key :: Str) -> Str {
  match jv.get_field(j, key) {
    Some(JStr(v)) => v,
    _ => "",
  }
}

fn fns_of(pkg :: jv.Json) -> List[jv.Json] {
  match jv.get_field(pkg, "functions") {
    Some(JList(xs)) => xs,
    _ => [],
  }
}

fn any_fn_matches(pkg :: jv.Json, q :: Str) -> Bool {
  list.fold(fns_of(pkg), false, fn (acc :: Bool, f :: jv.Json) -> Bool {
    acc or str.contains(str.to_lower(sfield(f, "sig")), q)
  })
}

fn pkg_matches(pkg :: jv.Json, q :: Str) -> Bool {
  if str.contains(str.to_lower(sfield(pkg, "name")), q) {
    true
  } else {
    if str.contains(str.to_lower(sfield(pkg, "description")), q) {
      true
    } else {
      any_fn_matches(pkg, q)
    }
  }
}

fn matched_sigs(pkg :: jv.Json, q :: Str) -> List[Str] {
  list.fold(fns_of(pkg), [], fn (acc :: List[Str], f :: jv.Json) -> List[Str] {
    let sig := sfield(f, "sig")
    if str.contains(str.to_lower(sig), q) {
      if list.len(acc) < 5 {
        list.concat(acc, [sig])
      } else {
        acc
      }
    } else {
      acc
    }
  })
}

fn format_pkg(pkg :: jv.Json, q :: Str) -> Str {
  let name := sfield(pkg, "name")
  let desc := sfield(pkg, "description")
  let repo := sfield(pkg, "repo")
  let sigs := matched_sigs(pkg, q)
  let sig_line := if list.is_empty(sigs) {
    ""
  } else {
    str.concat("\n    exports: ", str.join(sigs, "  |  "))
  }
  str.join(["• ", name, if str.is_empty(desc) {
    ""
  } else {
    str.concat(" — ", desc)
  }, "\n    depend: ", name, " = { git = \"", repo, "\" }", sig_line], "")
}

fn render(matches :: List[jv.Json], q :: Str, qraw :: Str) -> Str {
  if list.is_empty(matches) {
    str.join(["No existing Lex package matches \"", qraw, "\". Nothing to reuse — safe to build it."], "")
  } else {
    let body := str.join(list.map(matches, fn (p :: jv.Json) -> Str {
      format_pkg(p, q)
    }), "\n")
    str.join([int_str(list.len(matches)), " existing package(s) match \"", qraw, "\" — reuse before rebuilding:\n", body], "")
  }
}

fn int_str(n :: Int) -> Str {
  match n {
    0 => "0",
    _ => nonzero_int_str(n),
  }
}

fn nonzero_int_str(n :: Int) -> Str {
  if n <= 0 {
    ""
  } else {
    str.concat(nonzero_int_str(n / 10), digit(n % 10))
  }
}

fn digit(d :: Int) -> Str {
  match d {
    0 => "0",
    1 => "1",
    2 => "2",
    3 => "3",
    4 => "4",
    5 => "5",
    6 => "6",
    7 => "7",
    8 => "8",
    _ => "9",
  }
}

fn execute(args :: jv.Json) -> [io, net, proc] Result[jv.Json, e.Errors] {
  match util.field_str(args, "query") {
    None => Err(e.single("", "missing_field", "query is required")),
    Some(qraw) => {
      let q := str.to_lower(str.trim(qraw))
      match proc.run("curl", ["-fsSL", catalog_url()]) {
        Err(msg) => Err(e.single("", "proc_error", msg)),
        Ok(out) => match util.cli_result(out) {
          Err(detail) => Err(e.single("", "catalog_unavailable", util.unavailable("catalog fetch", detail))),
          Ok(body) => match jv.parse_into_errors(body) {
            Err(_) => Err(e.single("", "catalog_parse", "catalog.json did not parse")),
            Ok(cat) => match jv.get_field(cat, "packages") {
              Some(JList(pkgs)) => {
                let matches := list.filter(pkgs, fn (p :: jv.Json) -> Bool {
                  pkg_matches(p, q)
                })
                Ok(JStr(render(matches, q, qraw)))
              },
              _ => Err(e.single("", "catalog_shape", "catalog.json has no packages array")),
            },
          },
        },
      }
    },
  }
}

fn tool() -> t.Tool {
  t.define("find_packages", "Search existing Lex packages (name, description, exported functions) before writing new code, so you import and reuse instead of reinventing. Returns matching packages, how to depend on them, and the relevant function signatures.", params(), execute)
}

